### PR TITLE
fixed the 'starts' and add 'image' plots

### PR DESCRIPTION
**Pull request by svetlanabelitser**

### CODE REVIEW

**Comment by svetlanabelitser** [comment]
copied 08_T5_10_scri.R into my 'p_steps' and fixed it.

**Comment by DavideMessinaARS** [comment]
Did you merge the changes? I see you have closed the PR

**Comment by svetlanabelitser** [comment]
I changed it, and then deleted, and now changed again :))) It should work now.

**Comment by svetlanabelitser** [comment]
with the new pull request

**Comment by svetlanabelitser** [comment]
I didn't want to close it...

**Pull request closed without merging**
