### PR TITLE
new version of SCRI

### PR DESCRIPTION
**Pull request by svetlanabelitser**
the cdd

### CODE REVIEW

**Comment by DavideMessinaARS** [comment]
Did you start the fork from the main or SCCS?

**Comment by svetlanabelitser** [comment]
SCCS (I think). I was not sure what to choose: SCCS or development.

**Comment by DavideMessinaARS** [comment]
Depends on where the fork originated.
In the upper left corner of your repository, just under the name the should be a phrase like "forked from xxxxxx".

That tells you about the origin.

In addition, is the fork updated with the most recent changes from origin(xxxxxx)?

**Comment by svetlanabelitser** [comment]
image

First I've updated it

**Pull request closed without merging**
